# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "571d33433aeb76327f70abc32ab4ef132e01fd1f86f8ce3946765a0c2acc82a1171440c82d42a9b48dec3348776f9b3ec9e497e4b4afe81d3bc04cee6c357cad01"
genesis_address_str = "zQ5Y7eZ5CJj749Ltj9MQsHyUx4NQtMWfYh"
blockchain_pubkey_str = "022696ad3d8bd010e6cfdb7fede6cdf5b63a7b0ba5f861abce99642f7c8bf2cac0"
blockchain_seckey_str = ""
genesis_timestamp = 1578207105
default_connections = [
    "138.201.196.174:20100",
]
peer_list_url = "https://downloads.laqpay.net/blockchain/peers.txt"

[params]
distribution_addresses = [
    "2EuyufQijRLMNZExtXwdvSzezRdgefh2NwD"
]
