# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "571d33433aeb76327f70abc32ab4ef132e01fd1f86f8ce3946765a0c2acc82a1171440c82d42a9b48dec3348776f9b3ec9e497e4b4afe81d3bc04cee6c357cad01"
genesis_address_str = "zQ5Y7eZ5CJj749Ltj9MQsHyUx4NQtMWfYh"
blockchain_pubkey_str = "022696ad3d8bd010e6cfdb7fede6cdf5b63a7b0ba5f861abce99642f7c8bf2cac0"
blockchain_seckey_str = ""
genesis_timestamp = 1578207105
default_connections = [
    "138.201.196.174:6000",
]
peer_list_url = "https://downloads.laqpay.net/blockchain/peers.txt"

[params]
distribution_addresses = [
	"knuD1GNFxVq8h489g2EkixwnMMXdzJxRv2",
	"JTYGfZf9RAtLMX8fX9HQGvgdR43vmyte3e",
	"2DxDynFwsB4hLeENzDfT9Qusn6MR8ovVjJ9",
	"MrFhCebjazo3DYfwHxgzwdaiv4VWQ9fMfs",
	"4u68xDgjzLhFUEmHUwkViffDpYe4t5r3Nh",
	"QmUfKLGUEU8zDVdD1uznZmwwepakBcakzs",
	"2MKgrbu4XWiyAwUhSFybEM3dBr5RyqemLmU",
	"268AtZHvX2jTExbNbfZot2FrmAa4vKfgQzw",
	"SH6kbkb3wT7zoauwFCJfvppcr6B9h74vTz",
	"51EYGzABTuKWCebRBhQ8HKSVrnM3KZKmiV",
	"VjwnFi95XoEcdHGgCg3ocA4EZYxM6rZzs9",
	"2ZpdGTB1oefbVgUrfiBZoiZA5zjJ4ee6aR",
	"HpyjJmr3v7gsnd8oX5smaQSquhs8NeX7ga",
	"2KPU8jPr8fRRJpwhzTRpa8Ea3r7LQSgxuHm",
	"29C7LksK2twK3x7Wf2e5r8PgyrUoi7GSGzP",
	"2RSVhj6avAX7Cwo758n9d1q1vyefCpUZG9L",
	"jHDeaSumg8BY3LodRDctQua5A7pcmHqXAg",
	"2ZrwfqZSLu3witrjkJyfbf2SgCisdJw14Ap",
	"EDoj3jWPs7CXYM86CfNRcX5MwNr5RoUvNM",
	"QdJCYpaDATnP95uiGtv16tAofbB2pgMuRy",
	"29tpXB2czPxF251RzkgH7ZC3bhZH9DQct2A",
	"VN39PB65pciZBqSwmSVHAHkVf2LrkajbkG",
	"b34BYnh9TyicNZhzsyjvVwgD6bSeLfD8H3",
	"21R4G8QvyWr5MbpHgF7MCH9tmmAdomBB1YS",
	"28bwz5JNeqKKJfmqHDzQT2KPSJPwZZ3aTgB",
]
