#!/usr/bin/env bash

# Removes lib.a files cached under $GOPATH.
# Sometimes these are not regenerated by go when doing `go run`

rm ${GOPATH}/pkg/*/github.com/laqpay/laqpay/src/*.a
rm ${GOPATH}/pkg/*/github.com/laqpay/laqpay/src/lib/*.a
rm ${GOPATH}/pkg/*/github.com/laqpay/*.a
